"""empty message

Revision ID: 0363a7c28350
Revises: fef484557414
Create Date: 2019-05-17 17:07:56.511120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0363a7c28350'
down_revision = 'fef484557414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('last_modified_at', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('last_modified_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_created_at'), 'customer', ['created_at'], unique=False)
    op.create_index(op.f('ix_customer_last_modified_at'), 'customer', ['last_modified_at'], unique=False)
    op.drop_index('ix_customer_last_modify_at', table_name='customer')
    op.drop_index('ix_customer_last_modify_by', table_name='customer')
    op.drop_constraint('customer_ibfk_1', 'customer', type_='foreignkey')
    op.create_foreign_key(None, 'customer', 'user', ['last_modified_by'], ['id'])
    op.drop_column('customer', 'last_modify_at')
    op.drop_column('customer', 'last_modify_by')
    op.add_column('user', sa.Column('modified_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('modified_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_modified_at'), 'user', ['modified_at'], unique=False)
    op.drop_index('ix_user_modify_at', table_name='user')
    op.drop_constraint('user_ibfk_3', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user', ['modified_by'], ['id'])
    op.drop_column('user', 'modify_by')
    op.drop_column('user', 'modify_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('modify_at', mysql.DATETIME(), nullable=True))
    op.add_column('user', sa.Column('modify_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_ibfk_3', 'user', 'user', ['modify_by'], ['id'])
    op.create_index('ix_user_modify_at', 'user', ['modify_at'], unique=False)
    op.drop_index(op.f('ix_user_modified_at'), table_name='user')
    op.drop_column('user', 'modified_by')
    op.drop_column('user', 'modified_at')
    op.add_column('customer', sa.Column('last_modify_by', mysql.DATETIME(), nullable=True))
    op.add_column('customer', sa.Column('last_modify_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.create_foreign_key('customer_ibfk_1', 'customer', 'user', ['created_at'], ['id'])
    op.create_index('ix_customer_last_modify_by', 'customer', ['last_modify_by'], unique=False)
    op.create_index('ix_customer_last_modify_at', 'customer', ['last_modify_at'], unique=False)
    op.drop_index(op.f('ix_customer_last_modified_at'), table_name='customer')
    op.drop_index(op.f('ix_customer_created_at'), table_name='customer')
    op.drop_column('customer', 'last_modified_by')
    op.drop_column('customer', 'last_modified_at')
    # ### end Alembic commands ###
